// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'react-toggle': string;
  'react-toggle--checked': string;
  'react-toggle--disabled': string;
  'react-toggle--focus': string;
  'react-toggle-screenreader-only': string;
  'react-toggle-thumb': string;
  'react-toggle-track': string;
  'react-toggle-track-check': string;
  'react-toggle-track-x': string;
}
declare var cssExports: CssExports;
export = cssExports;
